spring:
  main:
    allow-bean-definition-overriding: true

  #파일 용량 조절
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/unme?autoReconnect=true
    username: root
    #localComputer MYSQL
    password: jongbin121!
    #MAC MYSQL :
    #password: 698427

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #ddl-auto: create-drop #????? ?? ???? ?? ??? ??? ?? ??
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true


  security:
    user:
      name: esanghaesee
      password: 1234

    oauth2:
      client:
        registration:
          google:
            client-id: 71318484453-sn62ah5b0rdiktov48jesea0us3vauph.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  header: Authorization
#  token-validity-in-seconds: 86400


# 유저 권한 떄문에 여기로 설정
file:
  path: C:\\myproject\\unme3\\src\\main\\resources\\static\\image\\

